version: '2'
services:
  nginx:
      image: nginx
      restart: always
      expose:
         - "80"
      ports:
          - "80:80"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      network_mode: "host"
      depends_on:
        - dabaappserver
  dabaappserver:
    image: node:6.13.0
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./srv:/app
      - ./dist:/dist
      - ./log:/log
    network_mode: "host"
    environment:
      - DEBUG=appsrv:*
      - MONGO_URL=mongodb://dabauser:daba159@127.0.0.1/daba
      - rooturl=http://api.nuistiot.com
      - listenport=30050
    ports:
       - "30050:30050"
    expose:
       - "30050"
