version: '2'
services:
    simulatortest:
      image: node:6.13.0
      restart: always
      command: node ./index.js
      working_dir: /app
      volumes:
        - ./simulator_test:/app
      network_mode: "host"
